name: Check Go code

on:
  push:
    paths:
      - ".github/workflows/check-go.yml"
      - "Taskfile.yml"
      - "manager/**"
  pull_request:
    paths:
      - ".github/workflows/check-go.yml"
      - "Taskfile.yml"
      - "manager/**"
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Lint
        run: task go:lint

      - name: Run tests
        run: task go:test

      - name: Check formatting
        run: task go:check-formatting
