name: Check documentation files

on:
  push:
    paths:
      - ".github/workflows/check-docs.yml"
      - "Taskfile.yml"
      - "**.md"
  pull_request:
    paths:
      - ".github/workflows/check-docs.yml"
      - "Taskfile.yml"
      - "**.md"
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install Taskfile
        uses: arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Check links
        run: task docs:check-links

      - name: Check formatting
        run: task docs:check-formatting
